<a href="https://colab.research.google.com/github/daveveed/Geo-Data-Science/blob/main/Geocoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import geopandas as gpd, pandas as pd, os

In [2]:
data_folder = 'data'
output_folder = 'output'

if not os.path.exists(data_folder):
  os.mkdir(data_folder)

if not os.path.exists(output_folder):
  os.mkdir(output_folder)

In [3]:
import requests

In [4]:
def downlaod(url):
  filename = os.path.join(data_folder, os.path.basename(url))

  if not os.path.exists(filename):
    response = requests.get(url, allow_redirects=True)

    with open(filename,'wb') as f:
      f.write(response.content)
    print('Downloaded :', filename)

In [5]:
url_path = 'https://raw.githubusercontent.com/daveveed/Geo-Data-Science/main/Data/Temp/addresses.txt'

downlaod(url_path)

Downloaded : data/addresses.txt

In [6]:
fp = os.path.join(data_folder, 'addresses.txt')

data = pd.read_csv(fp, sep=';')
data.head()

     id                                           addr
0  1000       Itämerenkatu 14, 00101 Helsinki, Finland
1  1001          Kampinkuja 1, 00100 Helsinki, Finland
2  1002           Kaivokatu 8, 00101 Helsinki, Finland
3  1003  Hermannin rantatie 1, 00580 Helsinki, Finland
4  1005     Tyynenmerenkatu 9, 00220 Helsinki, Finland

Now we have our data in a DataFrame and we can geocode our addresses using the the geopandas.tools.geocode() function in geopandas that uses geopy library under the hood. The function geocodes a list of addresses (strings) and returns a GeoDataFrame with the geocoded result. In the following, we import the geocode() function and geocode the addresses using Nominatim. Then we pass the addressess to the function from the column addr. We need to provide a custom string (name of your application) in the user_agent parameter to identify ourselves. We also use the timeout-parameter to specify how many seconds to wait for a response from the service:

In [7]:
from geopandas.tools import geocode

geo = geocode(
    data["addr"], provider="nominatim", user_agent="my_geocoding_app_colab", timeout=10
)
geo.head()

,geometry,address
0,POINT (24.91556 60.1632),"Ruoholahti, 14, Itämerenkatu, Ruoholahti, Läns..."
1,POINT (24.93166 60.16905),"Kamppi, 1, Kampinkuja, Kamppi, Eteläinen suurp..."
2,POINT (24.94153 60.17016),"Espresso House, 8, Kaivokatu, Keskusta, Kluuvi..."
3,POINT (24.97687 60.18748),"Kalasatama, 1, Hermannin rantatie, Suvilahti, ..."
4,POINT (24.92151 60.15662),"9, Tyynenmerenkatu, Jätkäsaari, Länsisatama, E..."

## Reverse Geocoding

In [8]:
points = geo[['geometry']].copy()

In [9]:
points.head()

                    geometry
0   POINT (24.91556 60.1632)
1  POINT (24.93166 60.16905)
2  POINT (24.94153 60.17016)
3  POINT (24.97687 60.18748)
4  POINT (24.92151 60.15662)

In [11]:
from geopandas.tools import reverse_geocode

reverse_geo = reverse_geocode(points.geometry, provider='nominatim', user_agent='my_geocoding_app_colab', timeout=10)
reverse_geo.head()

GeocoderRateLimited: Non-successful status code 429